configuration:
  chemin source: exemples/na/informations linguistiques.yml
base:
  chemin source: exemples/na/na.lex
  format d’entrée: MDF Alexis
  format de sortie: LMF Alexis
  identifiant: na
général:
  nom: Dictionnaire na
  auteur: Alexis Michaud
  commentaire: Test LMF-α
  ordre lexicographique: 
      - [ɑ, ɑ̃, æ, æ̃, b, ɕ, d, dz, dʑ, ɖ, ɖʐ, e, ɤ, ɤ̃, ə, f, g, ɣ, h, i, ĩ, j, jæ, jɤ, je, jo, ʝ, k, kʰ, l, ɭ, ɬ, m, n, ɳ, ɲ, ŋ, o, õ, p, pʰ, q, qʰ, ɻ, ɻ̍, ɻ ̍̃, ʁ, s, ʂ, t, tʰ, tɕ, tɕʰ, ts, tsʰ, ʈ, ʈʰ, ʈʂ, ʈʂʰ, u, ɯ, v, [ṽ̩, ṽ̩], w, wɑ, wæ, wɤ, wo, wɤ̃, w̃, w̃æ, z, ʐ, ʑ, x]
      - [˥, ˧, ˩, α, β, γ, "$", "#"]
      - chiffres
langues:
  nru:
      type de caractères: latin
      autoglossonyme: na
      glossonyme: na
      statut: source
  fra:
      type de caractères: latin
      autoglossonyme: français
      glossonyme: français
      statut: cible
  eng:
      type de caractères: latin
      autoglossonyme: English
      glossonyme: anglais
      statut: cible
  cmn:
      type de caractères: hanzi
      autoglossonyme: 普通话
      glossonyme: chinois
      statut: cible
XML:
  chemin cible: exemples/na/na.xml
  format: α #αβγ
  langue: fra
  XSL: style.xsl
  tri: normal
Latex:
  format: standard
  gabarit: exemples/na/latexFRA.xsl
  langue: fra
  chemin cible: exemples/na/résultats/naFRA.tex
  fichiers annexes:
    introduction: exemples/na/intro_fra.tex


